version: '3.8'

services:
  app:
    image: node:20.9.0
    command: sh -c "npm install && npm run build && npm run dev"
    ports:
      - "3005:3005"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app